### PR TITLE
add help box

### PR DESCRIPTION
**Pull request by potatowagon**
Unable to set default size of helpBox. helpBox is an instance of Alert
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Alert.html

used the methods 
helpBox.setHeight(500);
helpBox.setWidth(500);

but does not work.

screenshot 56
Current

screenshot 57
Ideal. Acheived this by manually resizing the box

User friendly features of help box: help box allows user to type in the command tray while help box is still in the foreground. So user can refer to helpbox while typing commands. Press esc to close helpbox

### CODE REVIEW

**Comment by pyokagan** [comment]
@potatowagon Any reason why you did not want to just use the web browser?

**Comment by potatowagon** [comment]
Paul please help to see why helpBox wont obey helpBox.setHeight(500); and
helpBox.setWidth(500);

**Comment by potatowagon** [comment]
so task tracker can work offline :)

**Comment by pyokagan** [comment]
@potatowagon Well, you could ask the web browser to load a local file...

Anyway, try:

``` diff
diff --git a/src/main/java/seedu/address/ui/HelpWindow.java b/src/main/java/seedu/address/ui/HelpWindow.java
index a8286e6..97aa7a4 100644
--- a/src/main/java/seedu/address/ui/HelpWindow.java
+++ b/src/main/java/seedu/address/ui/HelpWindow.java
@@ -54,8 +54,8 @@ public class HelpWindow {
         stage.setAlwaysOnTop(true);
         helpBox.initModality(Modality.NONE);
         helpBox.setResizable(true);
-        helpBox.setWidth(500.0);
-        helpBox.setHeight(500.0);
+        helpBox.getDialogPane().setPrefWidth(500.0);
+        helpBox.getDialogPane().setPrefHeight(500.0);
         //helpBox.getDialogPane().getScene().getWindow().sizeToScene();

         //set contents
```

**Comment by potatowagon** [comment]
oh hey it works ! thanks Paul

**Comment by potatowagon** [comment]
travis could not compile because of missing library, here it is: https://commons.apache.org/proper/commons-lang/download_lang.cgi?Preferred=http%3A%2F%2Fdownload.nus.edu.sg%2Fmirror%2Fapache%2F

the library is for the TableBuilder Class to print neat tables

**Comment by potatowagon** [comment]
another way to have neat tabes without the library would be to manually add spaces, aligning the rows in eclipse text editor does not lead to aligned rows in helpbox ui

**Pull request closed without merging**
