### PR TITLE
shift end time to be on the same line as start time

### PR DESCRIPTION
**Pull request by potatowagon**
screenshot 60

### CODE REVIEW

**Review by nightism — CHANGES_REQUESTED** [review]
better to narrow the event task card a little bit more ^_^

**Comment by pyokagan** [comment]
@potatowagon Will this be done by the end of Sunday? We really need to freeze all the UI changes so we can make screenshots.

**Review by pyokagan — APPROVED** [review]
Nevermind. This PR is an improvement, and I can't wait, so I will merge now.

If you all want to do any more tweaks, do a PR on top.

**Comment by pyokagan** [comment]
@potatowagon But really, watch out for your tabs vs spaces in your FXML files.

**Comment by pyokagan** [comment]
Merged as a634047f07976c0f9ae7ed0073004e37ff08ab3b

**Comment by potatowagon** [comment]
ok, will make it narrower

**Pull request closed without merging**
