### PR TITLE
Add collated files for each team member (Preview)

### PR DESCRIPTION
**Pull request by pyokagan**
@CS2103AUG2016-T11-C4/developers 

As you all know, for v0.4 we have to submit a list of code/docs contributions for each team member. Here is a preview of what the collated list looks like if it were generated right now.

(Or you can see it via https://github.com/pyokagan/CS2103AUG2016-T11-C4-main/tree/collate/collated)

Git is able to [track who modified which lines in a file](https://help.github.com/articles/using-git-blame-to-trace-changes-in-a-file/). Using this feature, we are able to piece together how much a person contributed to the _current_ state of a file.

For Java files, as long as over 50% of lines of a method belongs to you, the method will appear in your collate file.

For Markdown documents, as long as over 50% of lines in a level 1, 2 or 3 section belong to you, the section will appear in your collate file.

The code I use to generate the listing is at https://github.com/pyokagan/pykcollate (warning: really bad code :-P ) if you wish to audit it.

Please take a look at the files and see if there might be any errors. These files will be used as a guide for adding the final `//@@author` markers.

(This PR is just a preview and won't be merged. I will do another one closer to Thurs)

### CODE REVIEW

**Review by nightism — APPROVED** [review]
reviewed

**Comment by potatowagon** [comment]
Are you going to merge in any of my pull request for code? If you're never going to just say so from the beginning, spent so much time writing code but nothing ever gets accepted, its a big waste of my time. 

Undo redo was redone 4 times, took 5 days.

**Comment by pyokagan** [comment]
> its a big waste of my time

Hmph, you mean reviewing all your code doesn't take time and effort on my part?

I already outlined the exact conditions for merging of the pull request at the summary in every review -- pass existing tests, have a pleasant API and not have any obvious bugs (which you can easily prove by writing tests).

How hard is it to write tests for your code? Why are you resisting and making it frustrating for both parties?

**Comment by pyokagan** [comment]
> and not have any obvious bugs (which you can easily prove by writing tests).

And yes, it is extremely important that as little bugs are introduced into the code base as possible because every bug is a potential catastrophic failure (e.g. the application crashing during our two presentations.)

**Comment by potatowagon** [comment]
i dont know how to write test for undo redo, do i create a new TaskBook each time to simulate command inputs? 

Testing with the UI produces expected results

I need help with writing test for undo redo

**Comment by pyokagan** [comment]
> Undo redo was redone 4 times, took 5 days.

Time spent on it is not a good argument. That's a sunk cost fallacy.

Anyway, if you feel a PR is taking a long time to get in, you can always work on another issue. In fact, an efficient worker would be doing multiple issues at once.

**Comment by pyokagan** [comment]
Okie, let's close this PR because so it does not clutter up the "Pull Requests" list.

**Pull request closed without merging**
