### PR TITLE
Final userguide revision

### PR DESCRIPTION
**Pull request by potatowagon**
User guide: removed unused images and parameter keywords, fixed minor formatiing, final cleanup

### CODE REVIEW

**Comment by pyokagan** [comment]
@potatowagon Is this ready?

**Comment by potatowagon** [comment]
yes, sorry i forgot to add labels

**Comment by pyokagan** [comment]
@potatowagon The most important label is the `ReadyForReview` label

**Comment by potatowagon** [comment]
okay, i will rmb next time

**Pull request merged**
