### PR TITLE
logic: implement date and time parsers

### PR DESCRIPTION
**Pull request by pyokagan**
This PR implements a `DateTimeParser` that is able to parse dates and times as defined by the user guide.
- [1/3] [parser: implement DateParser](https://github.com/CS2103AUG2016-T11-C4/main/pull/47/commits/2715d26d0d900beacf17e3adce7cc6a903d3cf4a)
- [2/3] [parser: implement TimeParser](https://github.com/CS2103AUG2016-T11-C4/main/pull/47/commits/d32751ac4f98a9b30cf4355b06c8b8ad45d555bb)
- [3/3] [parser: implement DateTimeParser](https://github.com/CS2103AUG2016-T11-C4/main/pull/47/commits/f133879a8a77875957ddcb3f3de27876b712c2c7)

### CODE REVIEW

**Comment by pyokagan** [comment]
@nightism I pulled this out from #37.

I'll try to get this PR merged in by tonight so you are able to build on top of it.

**Comment by pyokagan** [comment]
Hmm, looking at the code, some reworking may need to be done. Let's see...

**Comment by pyokagan** [comment]
@nightism @potatowagon Okay I think this is ready. Can you all take a look to see if it adheres to the user guide?

**Comment by pyokagan** [comment]
@nightism @potatowagon ping ping ping. I want to get this in and go to sleep ><

**Review by nightism — APPROVED** [review]
reviewed already, no major issue found

**Review by potatowagon — APPROVED** [review]
looks good. please merge

**Comment by pyokagan** [comment]
@potatowagon @nightism Thanks, both.

**Pull request merged**
